# Generated by Django 4.2.7 on 2023-11-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flowershop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aneka_bunga', models.CharField(max_length=255)),
                ('warna', models.CharField(max_length=255)),
            ],
        ),
    ]
